#! /usr/bin/env perl

use IO::Socket ();
use JSON;

my $host = $ENV{'MATTDAEMON_HOST'} || 'localhost';
my $port = $ENV{'MATTDAEMON_PORT'} || '8090';
my $timeout = $ENV{'MATTDAEMON_TIMEOUT'} || 10;

my $data = {};

while (my $arg = shift @ARGV) {
	my ($k, $v) = split(/=/, $arg, 2);
	$data->{$k} = $v;
}

if (!$data->{type} || !$data->{core}) {
	die <<EOM
Syntax (examples):
./mattdaemon-query type=queue_status core=/var/www/qwikis/qwiki
./mattdaemon-query type=clear_queue core=/var/www/qwikis/qwiki department=SolrPlugin
EOM
}

# note: Timeout does not work when sending
if ( my $socket = new IO::Socket::INET->new(
	PeerAddr => $host,
	PeerPort => $port,
	Proto => 'tcp',
	Timeout => $timeout)
) {
	my $type = delete $data->{type};
	my $department = delete $data->{department};
	my $host = delete $data->{host};
	$host =~ s#^https?://##;
	my $core = delete $data->{core};
	$core =~ s#/bin/?$##;

	eval {
		local $SIG{ALRM} = sub { die 'Timed out'; };
		alarm $timeout;
		$socket->send(encode_json({
			type => $type,
			data => $data,
			host => $host,
			department => $department,
			core => $core,
		}));

		my $response;
		$socket->recv($response, 4096);
		alarm 0;
		print $response;
	};
	alarm 0;
	if($@) {
		warn "Daemon timed out!";
		exit 1;
	}
} else {
	warn( "Can not bind to TaskDaemon: $!" );
	exit 1;
};
