#!/bin/sh
### BEGIN INIT INFO
# Provides:          mattdaemon
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start mattdaemon.
### END INIT INFO
set -eu
##############################################################################
export FOSWIKI_ROOT="/var/www/qwikis/qwiki"
BIN="./mattdaemon"
PARAMS="-d"
PIDFILE=/var/run/mattdaemon.pid
WORKER_USER=www-data

. /lib/lsb/init-functions

##############################################################################

case "${1:-}" in
    start)
        if [ -f "$PIDFILE" ] ; then
            log_warning_msg "Warning: mattdaemon already running, doing nothing (PIDFILE $PIDFILE exists)"
            exit 1
        fi

        log_daemon_msg "Starting mattdaemon" "mattdaemon"
        set +e
        cd $FOSWIKI_ROOT
        cd tools

        su -c "cd $FOSWIKI_ROOT/tools; FOSWIKI_ROOT=$FOSWIKI_ROOT $BIN $PARAMS" www-data > $PIDFILE
        #start-stop-daemon -b --pidfile $PIDFILE --user $WORKER_USER -d $FOSWIKI_ROOT/tools --start --exec /usr/bin/perl --startas $BIN -- $PARAMS
        RC=$?
        set -e
        log_end_msg $RC
        ;;

    stop)
        if [ -f "$PIDFILE" ] ; then
            log_daemon_msg "Stopping mattdaemon" "mattdaemon"
            set +e
            start-stop-daemon -K -p $PIDFILE
            RC=$?
            rm -f $PIDFILE
            set -e
            log_end_msg $RC
        else
            log_success_msg "No mattdaemon running"
        fi
        ;;

    status)
        if [ -f "$PIDFILE" ]
        then
            PROCESS="$(cat $PIDFILE)"
            if ps -p $PROCESS > /dev/null
            then
                log_success_msg "mattdaemon with pid $PROCESS is running"
                exit 0
            else
                log_warning_msg "mattdaemon with pid $PROCESS is NOT running"
                exit 1
            fi
        else
            log_warning_msg "Could not find a running mattdaemon (no PID file)"
            exit 1
        fi
        ;;

    restart|reload|force-reload)
        $0 stop
        $0 start
        ;;

    *)
        echo "Usage: ${0:-} {start|stop|restart|reload|force-reload|status}" >&2
        exit 1
        ;;
esac

exit 0
